Cleanup whitespaces

diff --git a/nw-gre/install-sh b/nw-gre/install-sh
--- a/nw-gre/install-sh
+++ b/nw-gre/install-sh
@@ -137,36 +137,36 @@ while test $# -ne 0; do
     -d) dir_arg=true;;
 
     -g) chgrpcmd="$chgrpprog $2"
-	shift;;
+    shift;;
 
     --help) echo "$usage"; exit $?;;
 
     -m) mode=$2
-	case $mode in
-	  *' '* | *'	'* | *'
-'*	  | *'*'* | *'?'* | *'['*)
-	    echo "$0: invalid mode: $mode" >&2
-	    exit 1;;
-	esac
-	shift;;
+    case $mode in
+      *' '* | *'	'* | *'
+'*    | *'*'* | *'?'* | *'['*)
+        echo "$0: invalid mode: $mode" >&2
+        exit 1;;
+    esac
+    shift;;
 
     -o) chowncmd="$chownprog $2"
-	shift;;
+    shift;;
 
     -s) stripcmd=$stripprog;;
 
     -t) dst_arg=$2
-	shift;;
+    shift;;
 
     -T) no_target_directory=true;;
 
     --version) echo "$0 $scriptversion"; exit $?;;
 
     --)	shift
-	break;;
+    break;;
 
     -*)	echo "$0: invalid option: $1" >&2
-	exit 1;;
+    exit 1;;
 
     *)  break;;
   esac
@@ -211,16 +211,16 @@ if test -z "$dir_arg"; then
 
     *[0-7])
       if test -z "$stripcmd"; then
-	u_plus_rw=
+    u_plus_rw=
       else
-	u_plus_rw='% 200'
+    u_plus_rw='% 200'
       fi
       cp_umask=`expr '(' 777 - $mode % 1000 ')' $u_plus_rw`;;
     *)
       if test -z "$stripcmd"; then
-	u_plus_rw=
+    u_plus_rw=
       else
-	u_plus_rw=,u+rw
+    u_plus_rw=,u+rw
       fi
       cp_umask=$mode$u_plus_rw;;
   esac
@@ -263,8 +263,8 @@ do
     # if double slashes aren't ignored.
     if test -d "$dst"; then
       if test -n "$no_target_directory"; then
-	echo "$0: $dst_arg: Is a directory" >&2
-	exit 1
+    echo "$0: $dst_arg: Is a directory" >&2
+    exit 1
       fi
       dstdir=$dst
       dst=$dstdir/`basename "$src"`
@@ -272,29 +272,29 @@ do
     else
       # Prefer dirname, but fall back on a substitute if dirname fails.
       dstdir=`
-	(dirname "$dst") 2>/dev/null ||
-	expr X"$dst" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
-	     X"$dst" : 'X\(//\)[^/]' \| \
-	     X"$dst" : 'X\(//\)$' \| \
-	     X"$dst" : 'X\(/\)' \| . 2>/dev/null ||
-	echo X"$dst" |
-	    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
-		   s//\1/
-		   q
-		 }
-		 /^X\(\/\/\)[^/].*/{
-		   s//\1/
-		   q
-		 }
-		 /^X\(\/\/\)$/{
-		   s//\1/
-		   q
-		 }
-		 /^X\(\/\).*/{
-		   s//\1/
-		   q
-		 }
-		 s/.*/./; q'
+    (dirname "$dst") 2>/dev/null ||
+    expr X"$dst" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+         X"$dst" : 'X\(//\)[^/]' \| \
+         X"$dst" : 'X\(//\)$' \| \
+         X"$dst" : 'X\(/\)' \| . 2>/dev/null ||
+    echo X"$dst" |
+        sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
+           s//\1/
+           q
+         }
+         /^X\(\/\/\)[^/].*/{
+           s//\1/
+           q
+         }
+         /^X\(\/\/\)$/{
+           s//\1/
+           q
+         }
+         /^X\(\/\).*/{
+           s//\1/
+           q
+         }
+         s/.*/./; q'
       `
 
       test -d "$dstdir"
@@ -307,74 +307,74 @@ do
   if test $dstdir_status != 0; then
     case $posix_mkdir in
       '')
-	# Create intermediate dirs using mode 755 as modified by the umask.
-	# This is like FreeBSD 'install' as of 1997-10-28.
-	umask=`umask`
-	case $stripcmd.$umask in
-	  # Optimize common cases.
-	  *[2367][2367]) mkdir_umask=$umask;;
-	  .*0[02][02] | .[02][02] | .[02]) mkdir_umask=22;;
+    # Create intermediate dirs using mode 755 as modified by the umask.
+    # This is like FreeBSD 'install' as of 1997-10-28.
+    umask=`umask`
+    case $stripcmd.$umask in
+      # Optimize common cases.
+      *[2367][2367]) mkdir_umask=$umask;;
+      .*0[02][02] | .[02][02] | .[02]) mkdir_umask=22;;
 
-	  *[0-7])
-	    mkdir_umask=`expr $umask + 22 \
-	      - $umask % 100 % 40 + $umask % 20 \
-	      - $umask % 10 % 4 + $umask % 2
-	    `;;
-	  *) mkdir_umask=$umask,go-w;;
-	esac
+      *[0-7])
+        mkdir_umask=`expr $umask + 22 \
+          - $umask % 100 % 40 + $umask % 20 \
+          - $umask % 10 % 4 + $umask % 2
+        `;;
+      *) mkdir_umask=$umask,go-w;;
+    esac
 
-	# With -d, create the new directory with the user-specified mode.
-	# Otherwise, rely on $mkdir_umask.
-	if test -n "$dir_arg"; then
-	  mkdir_mode=-m$mode
-	else
-	  mkdir_mode=
-	fi
+    # With -d, create the new directory with the user-specified mode.
+    # Otherwise, rely on $mkdir_umask.
+    if test -n "$dir_arg"; then
+      mkdir_mode=-m$mode
+    else
+      mkdir_mode=
+    fi
 
-	posix_mkdir=false
-	case $umask in
-	  *[123567][0-7][0-7])
-	    # POSIX mkdir -p sets u+wx bits regardless of umask, which
-	    # is incompatible with FreeBSD 'install' when (umask & 300) != 0.
-	    ;;
-	  *)
-	    tmpdir=${TMPDIR-/tmp}/ins$RANDOM-$$
-	    trap 'ret=$?; rmdir "$tmpdir/d" "$tmpdir" 2>/dev/null; exit $ret' 0
+    posix_mkdir=false
+    case $umask in
+      *[123567][0-7][0-7])
+        # POSIX mkdir -p sets u+wx bits regardless of umask, which
+        # is incompatible with FreeBSD 'install' when (umask & 300) != 0.
+        ;;
+      *)
+        tmpdir=${TMPDIR-/tmp}/ins$RANDOM-$$
+        trap 'ret=$?; rmdir "$tmpdir/d" "$tmpdir" 2>/dev/null; exit $ret' 0
 
-	    if (umask $mkdir_umask &&
-		exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1
-	    then
-	      if test -z "$dir_arg" || {
-		   # Check for POSIX incompatibilities with -m.
-		   # HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- or
-		   # other-writeable bit of parent directory when it shouldn't.
-		   # FreeBSD 6.1 mkdir -m -p sets mode of existing directory.
-		   ls_ld_tmpdir=`ls -ld "$tmpdir"`
-		   case $ls_ld_tmpdir in
-		     d????-?r-*) different_mode=700;;
-		     d????-?--*) different_mode=755;;
-		     *) false;;
-		   esac &&
-		   $mkdirprog -m$different_mode -p -- "$tmpdir" && {
-		     ls_ld_tmpdir_1=`ls -ld "$tmpdir"`
-		     test "$ls_ld_tmpdir" = "$ls_ld_tmpdir_1"
-		   }
-		 }
-	      then posix_mkdir=:
-	      fi
-	      rmdir "$tmpdir/d" "$tmpdir"
-	    else
-	      # Remove any dirs left behind by ancient mkdir implementations.
-	      rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null
-	    fi
-	    trap '' 0;;
-	esac;;
+        if (umask $mkdir_umask &&
+        exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1
+        then
+          if test -z "$dir_arg" || {
+           # Check for POSIX incompatibilities with -m.
+           # HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- or
+           # other-writeable bit of parent directory when it shouldn't.
+           # FreeBSD 6.1 mkdir -m -p sets mode of existing directory.
+           ls_ld_tmpdir=`ls -ld "$tmpdir"`
+           case $ls_ld_tmpdir in
+             d????-?r-*) different_mode=700;;
+             d????-?--*) different_mode=755;;
+             *) false;;
+           esac &&
+           $mkdirprog -m$different_mode -p -- "$tmpdir" && {
+             ls_ld_tmpdir_1=`ls -ld "$tmpdir"`
+             test "$ls_ld_tmpdir" = "$ls_ld_tmpdir_1"
+           }
+         }
+          then posix_mkdir=:
+          fi
+          rmdir "$tmpdir/d" "$tmpdir"
+        else
+          # Remove any dirs left behind by ancient mkdir implementations.
+          rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null
+        fi
+        trap '' 0;;
+    esac;;
     esac
 
     if
       $posix_mkdir && (
-	umask $mkdir_umask &&
-	$doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir"
+    umask $mkdir_umask &&
+    $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir"
       )
     then :
     else
@@ -384,9 +384,9 @@ do
       # directory the slow way, step by step, checking for races as we go.
 
       case $dstdir in
-	/*) prefix='/';;
-	-*) prefix='./';;
-	*)  prefix='';;
+    /*) prefix='/';;
+    -*) prefix='./';;
+    *)  prefix='';;
       esac
 
       eval "$initialize_posix_glob"
@@ -403,34 +403,34 @@ do
 
       for d
       do
-	test -z "$d" && continue
+    test -z "$d" && continue
 
-	prefix=$prefix$d
-	if test -d "$prefix"; then
-	  prefixes=
-	else
-	  if $posix_mkdir; then
-	    (umask=$mkdir_umask &&
-	     $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir") && break
-	    # Don't fail if two instances are running concurrently.
-	    test -d "$prefix" || exit 1
-	  else
-	    case $prefix in
-	      *\'*) qprefix=`echo "$prefix" | sed "s/'/'\\\\\\\\''/g"`;;
-	      *) qprefix=$prefix;;
-	    esac
-	    prefixes="$prefixes '$qprefix'"
-	  fi
-	fi
-	prefix=$prefix/
+    prefix=$prefix$d
+    if test -d "$prefix"; then
+      prefixes=
+    else
+      if $posix_mkdir; then
+        (umask=$mkdir_umask &&
+         $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir") && break
+        # Don't fail if two instances are running concurrently.
+        test -d "$prefix" || exit 1
+      else
+        case $prefix in
+          *\'*) qprefix=`echo "$prefix" | sed "s/'/'\\\\\\\\''/g"`;;
+          *) qprefix=$prefix;;
+        esac
+        prefixes="$prefixes '$qprefix'"
+      fi
+    fi
+    prefix=$prefix/
       done
 
       if test -n "$prefixes"; then
-	# Don't fail if two instances are running concurrently.
-	(umask $mkdir_umask &&
-	 eval "\$doit_exec \$mkdirprog $prefixes") ||
-	  test -d "$dstdir" || exit 1
-	obsolete_mkdir_used=true
+    # Don't fail if two instances are running concurrently.
+    (umask $mkdir_umask &&
+     eval "\$doit_exec \$mkdirprog $prefixes") ||
+      test -d "$dstdir" || exit 1
+    obsolete_mkdir_used=true
       fi
     fi
   fi
@@ -486,24 +486,24 @@ do
       # to itself, or perhaps because mv is so ancient that it does not
       # support -f.
       {
-	# Now remove or move aside any old file at destination location.
-	# We try this two ways since rm can't unlink itself on some
-	# systems and the destination file might be busy for other
-	# reasons.  In this case, the final cleanup might fail but the new
-	# file should still install successfully.
-	{
-	  test ! -f "$dst" ||
-	  $doit $rmcmd -f "$dst" 2>/dev/null ||
-	  { $doit $mvcmd -f "$dst" "$rmtmp" 2>/dev/null &&
-	    { $doit $rmcmd -f "$rmtmp" 2>/dev/null; :; }
-	  } ||
-	  { echo "$0: cannot unlink or rename $dst" >&2
-	    (exit 1); exit 1
-	  }
-	} &&
+    # Now remove or move aside any old file at destination location.
+    # We try this two ways since rm can't unlink itself on some
+    # systems and the destination file might be busy for other
+    # reasons.  In this case, the final cleanup might fail but the new
+    # file should still install successfully.
+    {
+      test ! -f "$dst" ||
+      $doit $rmcmd -f "$dst" 2>/dev/null ||
+      { $doit $mvcmd -f "$dst" "$rmtmp" 2>/dev/null &&
+        { $doit $rmcmd -f "$rmtmp" 2>/dev/null; :; }
+      } ||
+      { echo "$0: cannot unlink or rename $dst" >&2
+        (exit 1); exit 1
+      }
+    } &&
 
-	# Now rename the file to the real destination.
-	$doit $mvcmd "$dsttmp" "$dst"
+    # Now rename the file to the real destination.
+    $doit $mvcmd "$dsttmp" "$dst"
       }
     fi || exit 1
 
